logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  
  # Configuración optimizada de base de datos
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 300000  # 5 minutos
      idle-timeout: 60000   # 1 minuto
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  # Configuración de JPA optimizada
  jpa:
    hibernate:
      ddl-auto: validate  # No recrear tablas
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  
  # Configuración de caché optimizada
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=300s

# Configuración de memoria optimizada
server:
  tomcat:
    threads:
      max: 20
      min-spare: 5
    max-connections: 100
    accept-count: 10
