service: todolist-api

provider:
  name: aws
  runtime: java11
  region: us-east-1
  memorySize: 512
  timeout: 30

functions:
  taskHandler:
    handler: com.tonilr.ToDoList.lambda.TaskLambdaHandler
    events:
      - http:
          path: /api/tasks
          method: get
          cors: true
      - http:
          path: /api/tasks
          method: post
          cors: true
      - http:
          path: /api/tasks/{id}
          method: put
          cors: true
      - http:
          path: /api/tasks/{id}
          method: delete
          cors: true

plugins:
  - serverless-offline
  - serverless-java-maven
