service: todolist-backend

frameworkVersion: '4'

provider:
  name: aws
  runtime: java17
  region: eu-north-1
  memorySize: 512
  timeout: 30
  environment:
    SPRING_PROFILES_ACTIVE: prod
    DB_HOST: ${ssm:/todolist/DB_HOST}
    DB_NAME: ${ssm:/todolist/DB_NAME}
    DB_USER: ${ssm:/todolist/DB_USER}
    DB_PASSWORD: ${ssm:/todolist/DB_PASSWORD}
    JWT_SECRET: ${ssm:/todolist/JWT_SECRET}
    JWT_EXPIRATION: 86400000

package:
  artifact: target/ToDoList-0.0.1-SNAPSHOT.jar
  individually: true

functions:
  api:
    handler: com.tonilr.ToDoList.lambda.LambdaHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-warmup

custom:
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true 